package workflow

import (
	"os"
	"path/filepath"
	"testing"
)

// TestFindModelFileWithRelativePath tests that FindModelFile works with a relative directory path
// This is the regression test for issue #46 where filepath.Rel was returning an error
// because dir was relative and absPath was absolute, causing an empty string to be returned.
func TestFindModelFileWithRelativePath(t *testing.T) {
	// Create a temporary directory with a model.joblib file
	tmpDir, err := os.MkdirTemp("", "model-format-test")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Create a models/iris subdirectory
	modelDir := filepath.Join(tmpDir, "models", "iris")
	if err := os.MkdirAll(modelDir, 0755); err != nil {
		t.Fatalf("failed to create model dir: %v", err)
	}

	// Create a model.joblib file
	modelFile := filepath.Join(modelDir, "model.joblib")
	if err := os.WriteFile(modelFile, []byte("test model data"), 0644); err != nil {
		t.Fatalf("failed to create model file: %v", err)
	}

	// Create some other files that should be skipped
	if err := os.WriteFile(filepath.Join(modelDir, "config.json"), []byte("{}"), 0644); err != nil {
		t.Fatalf("failed to create config.json: %v", err)
	}
	if err := os.WriteFile(filepath.Join(modelDir, "manifest.json"), []byte("{}"), 0644); err != nil {
		t.Fatalf("failed to create manifest.json: %v", err)
	}

	// Test with relative path
	relPath := "models/iris"
	// Change to tmpDir so the relative path works
	oldCwd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get current directory: %v", err)
	}
	defer os.Chdir(oldCwd)

	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("failed to change to tmp dir: %v", err)
	}

	result := FindModelFile(relPath)
	if result == "" {
		t.Errorf("FindModelFile returned empty string for directory %s containing model.joblib", relPath)
	}
	if result != "model.joblib" {
		t.Errorf("FindModelFile returned %q, expected %q", result, "model.joblib")
	}
}

// TestFindModelFileWithAbsolutePath tests FindModelFile with an absolute path
func TestFindModelFileWithAbsolutePath(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "model-format-test-abs")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Create a model.joblib file
	modelFile := filepath.Join(tmpDir, "model.joblib")
	if err := os.WriteFile(modelFile, []byte("test model data"), 0644); err != nil {
		t.Fatalf("failed to create model file: %v", err)
	}

	result := FindModelFile(tmpDir)
	if result == "" {
		t.Errorf("FindModelFile returned empty string for directory %s containing model.joblib", tmpDir)
	}
	if result != "model.joblib" {
		t.Errorf("FindModelFile returned %q, expected %q", result, "model.joblib")
	}
}

// TestFindModelFileSkipsGeneratedFiles tests that FindModelFile skips files generated by model-cli
func TestFindModelFileSkipsGeneratedFiles(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "model-format-test-skip")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Create only generated files (no actual model)
	if err := os.WriteFile(filepath.Join(tmpDir, "config.json"), []byte("{}"), 0644); err != nil {
		t.Fatalf("failed to create config.json: %v", err)
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "manifest.json"), []byte("{}"), 0644); err != nil {
		t.Fatalf("failed to create manifest.json: %v", err)
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "sbom.spdx-json"), []byte("{}"), 0644); err != nil {
		t.Fatalf("failed to create sbom.spdx-json: %v", err)
	}
	if err := os.WriteFile(filepath.Join(tmpDir, "mof.json"), []byte("{}"), 0644); err != nil {
		t.Fatalf("failed to create mof.json: %v", err)
	}

	result := FindModelFile(tmpDir)
	if result != "" {
		t.Errorf("FindModelFile returned %q for directory with only generated files, expected empty string", result)
	}
}

// TestDetectModelFormatFromPath tests that DetectModelFormatFromPath correctly identifies model formats
func TestDetectModelFormatFromPath(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "model-format-detect")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Create a sklearn model directory
	sklDir := filepath.Join(tmpDir, "sklearn")
	if err := os.MkdirAll(sklDir, 0755); err != nil {
		t.Fatalf("failed to create sklearn dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(sklDir, "model.joblib"), []byte("data"), 0644); err != nil {
		t.Fatalf("failed to create model.joblib: %v", err)
	}

	format := DetectModelFormatFromPath(sklDir)
	if format != ModelFormatSklearn {
		t.Errorf("DetectModelFormatFromPath returned %q for .joblib file, expected %q", format, ModelFormatSklearn)
	}
}
