package workflow

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// writeModelDir creates a model directory with the given files (relative
// paths, subdirectories allowed) and returns its path.
func writeModelDir(t *testing.T, files ...string) string {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "my-model")
	for _, f := range files {
		p := filepath.Join(dir, f)
		if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte("content of "+f), 0644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

const (
	storedManifest = `{"schemaVersion":2,"mediaType":"application/vnd.oci.image.manifest.v1+json",` +
		`"artifactType":"application/vnd.cncf.model.manifest.v1+json",` +
		`"config":{"mediaType":"application/vnd.cncf.model.config.v1+json","digest":"sha256:aaaa","size":1},` +
		`"layers":[{"mediaType":"application/vnd.cncf.model.weight.v1.raw","digest":"sha256:bbbb","size":2}],` +
		`"annotations":{"org.cncf.modctl.modelfile":"NAME my-model\n"}}`
	descriptor = `{"mediaType":"application/vnd.oci.image.manifest.v1+json","digest":"` + testDigest + `","size":512}`
)

// argv splits a recorded fake-tool call into its arguments.
func argv(t *testing.T, call string) []string {
	t.Helper()
	_, args, _ := strings.Cut(call, "\t")
	return strings.Fields(args)
}

func TestModelPackPushBuildsPushesAndAnnotates(t *testing.T) {
	modctl := installFakeTool(t, "modctl", []string{""}, 0)
	// fetch manifest, push annotated manifest, fetch descriptor
	oras := installFakeTool(t, "oras", []string{storedManifest, "", descriptor}, 0)

	modelDir := writeModelDir(t, "model.safetensors", "config.json", "README.md", "sub/weights.bin", ".hidden/secret")

	digest, err := (&ModelPackProvider{}).Push("my-model:v1", "ghcr.io/my-org", modelDir, map[string]string{
		AnnotationArtifactType: "model",
		AnnotationRuntime:      "vllm",
	})
	if err != nil {
		t.Fatalf("Push() error = %v", err)
	}
	if digest != testDigest {
		t.Errorf("Push() digest = %q, want the annotated manifest's digest %q", digest, testDigest)
	}

	calls := modctl.calls()
	if len(calls) != 2 {
		t.Fatalf("expected modctl build then push, got %d calls: %v", len(calls), calls)
	}
	build := argv(t, calls[0])
	if len(build) != 6 || build[0] != "build" || build[1] != "-t" || build[2] != "ghcr.io/my-org/my-model:v1" ||
		build[3] != "-f" || filepath.Base(build[4]) != "Modelfile" || build[5] != modelDir {
		t.Errorf("modctl build args = %v, want build -t ghcr.io/my-org/my-model:v1 -f <tmp>/Modelfile %s", build, modelDir)
	}
	if len(build) == 6 && strings.HasPrefix(build[4], modelDir) {
		t.Errorf("generated Modelfile %s was written into the model directory", build[4])
	}
	wantModelfile := "# Generated by model-cli for modctl build\n" +
		"NAME my-model\n" +
		"DOC README.md\n" +
		"CONFIG config.json\n" +
		"MODEL model.safetensors\n" +
		"MODEL sub/weights.bin\n"
	if got := string(modctl.file(t, 0, "Modelfile")); got != wantModelfile {
		t.Errorf("Modelfile =\n%s\nwant\n%s", got, wantModelfile)
	}
	if push := argv(t, calls[1]); !reflect.DeepEqual(push, []string{"push", "ghcr.io/my-org/my-model:v1"}) {
		t.Errorf("modctl push args = %v", push)
	}

	orasCalls := oras.calls()
	if len(orasCalls) != 3 {
		t.Fatalf("expected oras manifest fetch, manifest push, descriptor fetch; got %d calls: %v", len(orasCalls), orasCalls)
	}
	if got := argv(t, orasCalls[0]); !reflect.DeepEqual(got, []string{"manifest", "fetch", "ghcr.io/my-org/my-model:v1"}) {
		t.Errorf("oras call 0 = %v, want manifest fetch", got)
	}
	if got := argv(t, orasCalls[1]); len(got) != 4 || got[0] != "manifest" || got[1] != "push" ||
		got[2] != "ghcr.io/my-org/my-model:v1" || filepath.Base(got[3]) != "manifest.json" {
		t.Errorf("oras call 1 = %v, want manifest push ghcr.io/my-org/my-model:v1 <tmp>/manifest.json", got)
	}
	if got := argv(t, orasCalls[2]); !reflect.DeepEqual(got, []string{"manifest", "fetch", "--descriptor", "ghcr.io/my-org/my-model:v1"}) {
		t.Errorf("oras call 2 = %v, want descriptor fetch", got)
	}

	// The re-pushed manifest is the stored one plus the CNCF annotations.
	var pushed struct {
		SchemaVersion int               `json:"schemaVersion"`
		MediaType     string            `json:"mediaType"`
		ArtifactType  string            `json:"artifactType"`
		Layers        []json.RawMessage `json:"layers"`
		Annotations   map[string]string `json:"annotations"`
	}
	if err := json.Unmarshal(oras.file(t, 1, "manifest.json"), &pushed); err != nil {
		t.Fatalf("pushed manifest is not JSON: %v", err)
	}
	if pushed.SchemaVersion != 2 || pushed.MediaType != "application/vnd.oci.image.manifest.v1+json" ||
		pushed.ArtifactType != "application/vnd.cncf.model.manifest.v1+json" || len(pushed.Layers) != 1 {
		t.Errorf("pushed manifest lost fields: %+v", pushed)
	}
	wantAnnotations := map[string]string{
		"org.cncf.modctl.modelfile": "NAME my-model\n",
		AnnotationArtifactType:      "model",
		AnnotationRuntime:           "vllm",
	}
	if !reflect.DeepEqual(pushed.Annotations, wantAnnotations) {
		t.Errorf("pushed annotations = %v, want %v", pushed.Annotations, wantAnnotations)
	}
}

func TestModelPackPushUsesExistingModelfile(t *testing.T) {
	modctl := installFakeTool(t, "modctl", []string{""}, 0)
	installFakeTool(t, "oras", []string{descriptor}, 0)

	modelDir := writeModelDir(t, "model.safetensors", "Modelfile")

	if _, err := (&ModelPackProvider{}).Push("my-model:v1", "ghcr.io/my-org", modelDir, nil); err != nil {
		t.Fatalf("Push() error = %v", err)
	}
	want := []string{"build", "-t", "ghcr.io/my-org/my-model:v1", "-f", filepath.Join(modelDir, "Modelfile"), modelDir}
	if got := argv(t, modctl.calls()[0]); !reflect.DeepEqual(got, want) {
		t.Errorf("modctl build args = %v, want %v", got, want)
	}
}

func TestModelPackPushWithoutAnnotationsOnlyReadsDigest(t *testing.T) {
	installFakeTool(t, "modctl", []string{""}, 0)
	oras := installFakeTool(t, "oras", []string{descriptor}, 0)

	digest, err := (&ModelPackProvider{}).Push("my-model:v1", "ghcr.io/my-org", writeModelDir(t, "model.bin"), nil)
	if err != nil {
		t.Fatalf("Push() error = %v", err)
	}
	if digest != testDigest {
		t.Errorf("Push() digest = %q, want %q", digest, testDigest)
	}
	calls := oras.calls()
	if len(calls) != 1 || !reflect.DeepEqual(argv(t, calls[0]), []string{"manifest", "fetch", "--descriptor", "ghcr.io/my-org/my-model:v1"}) {
		t.Errorf("oras calls = %v, want only the descriptor fetch", calls)
	}
}

func TestModelPackPushUsesPlainHTTPForLocalRegistry(t *testing.T) {
	modctl := installFakeTool(t, "modctl", []string{""}, 0)
	installFakeTool(t, "oras", []string{descriptor}, 0)

	modelDir := writeModelDir(t, "model.bin")
	if _, err := (&ModelPackProvider{}).Push("e2e/my-model:v1", "localhost:5000", modelDir, nil); err != nil {
		t.Fatalf("Push() error = %v", err)
	}
	calls := modctl.calls()
	build := argv(t, calls[0])
	if len(build) != 7 || build[5] != "--plain-http" || build[2] != "localhost:5000/e2e/my-model:v1" {
		t.Errorf("modctl build args = %v, want --plain-http before the context dir", build)
	}
	if push := argv(t, calls[1]); !reflect.DeepEqual(push, []string{"push", "--plain-http", "localhost:5000/e2e/my-model:v1"}) {
		t.Errorf("modctl push args = %v", push)
	}
}

func TestModelPackPushPackagesSingleFileFromParentDir(t *testing.T) {
	modctl := installFakeTool(t, "modctl", []string{""}, 0)
	installFakeTool(t, "oras", []string{descriptor}, 0)

	modelDir := writeModelDir(t, "model.gguf")
	file := filepath.Join(modelDir, "model.gguf")
	if _, err := (&ModelPackProvider{}).Push("my-model:v1", "ghcr.io/my-org", file, nil); err != nil {
		t.Fatalf("Push() error = %v", err)
	}
	build := argv(t, modctl.calls()[0])
	if len(build) != 6 || build[5] != modelDir {
		t.Errorf("modctl build args = %v, want the file's parent %s as context", build, modelDir)
	}
	if got := string(modctl.file(t, 0, "Modelfile")); !strings.HasSuffix(got, "NAME my-model\nMODEL model.gguf\n") {
		t.Errorf("Modelfile =\n%s\nwant a single MODEL model.gguf entry", got)
	}
}

func TestModelPackPushReportsBuildFailure(t *testing.T) {
	modctl := installFakeTool(t, "modctl", []string{""}, 1)
	oras := installFakeTool(t, "oras", []string{descriptor}, 0)

	_, err := (&ModelPackProvider{}).Push("my-model:v1", "ghcr.io/my-org", writeModelDir(t, "model.bin"), map[string]string{"k": "v"})
	if err == nil || !strings.Contains(err.Error(), "failed to build with modctl") {
		t.Errorf("Push() error = %v, want a modctl build failure", err)
	}
	if n := len(modctl.calls()); n != 1 {
		t.Errorf("modctl was invoked %d times after a failed build, want 1", n)
	}
	if calls := oras.calls(); len(calls) != 0 {
		t.Errorf("oras should not run after a failed build, got %v", calls)
	}
}

func TestModelPackPushReportsAnnotationFailure(t *testing.T) {
	installFakeTool(t, "modctl", []string{""}, 0)
	installFakeTool(t, "oras", []string{"not json"}, 0)

	_, err := (&ModelPackProvider{}).Push("my-model:v1", "ghcr.io/my-org", writeModelDir(t, "model.bin"), map[string]string{"k": "v"})
	if err == nil || !strings.Contains(err.Error(), "failed to annotate manifest") {
		t.Errorf("Push() error = %v, want an annotation failure", err)
	}
}

func TestModelPackPushRejectsMissingSource(t *testing.T) {
	modctl := installFakeTool(t, "modctl", []string{""}, 0)
	installFakeTool(t, "oras", []string{descriptor}, 0)

	_, err := (&ModelPackProvider{}).Push("my-model:v1", "ghcr.io/my-org", filepath.Join(t.TempDir(), "missing"), nil)
	if err == nil {
		t.Fatal("Push() with a missing source path should fail")
	}
	if calls := modctl.calls(); len(calls) != 0 {
		t.Errorf("modctl should not run for a missing source, got %v", calls)
	}
}

func TestModelPackPushRejectsEmptyDirectory(t *testing.T) {
	modctl := installFakeTool(t, "modctl", []string{""}, 0)
	installFakeTool(t, "oras", []string{descriptor}, 0)

	_, err := (&ModelPackProvider{}).Push("my-model:v1", "ghcr.io/my-org", t.TempDir(), nil)
	if err == nil || !strings.Contains(err.Error(), "no files to package") {
		t.Errorf("Push() error = %v, want a no-files error", err)
	}
	if calls := modctl.calls(); len(calls) != 0 {
		t.Errorf("modctl should not run for an empty directory, got %v", calls)
	}
}

func TestModelPackPushNeedsORAS(t *testing.T) {
	installFakeTool(t, "modctl", []string{""}, 0)
	t.Setenv("PATH", filepath.Dir(lookPathOrSkip(t, "modctl")))

	_, err := (&ModelPackProvider{}).Push("my-model:v1", "ghcr.io/my-org", writeModelDir(t, "model.bin"), nil)
	if err == nil || !strings.Contains(err.Error(), "needs oras") {
		t.Errorf("Push() error = %v, want a missing-oras error", err)
	}
}

func lookPathOrSkip(t *testing.T, name string) string {
	t.Helper()
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if fileExists(filepath.Join(dir, name)) {
			return filepath.Join(dir, name)
		}
	}
	t.Skipf("%s not on PATH", name)
	return ""
}

func TestModelPackPull(t *testing.T) {
	modctl := installFakeTool(t, "modctl", []string{""}, 0)

	p := &ModelPackProvider{}
	if err := p.Pull("my-model:v1", "ghcr.io/my-org"); err != nil {
		t.Fatalf("Pull() error = %v", err)
	}
	if err := p.Pull("my-model:v1", "127.0.0.1:5000"); err != nil {
		t.Fatalf("Pull() error = %v", err)
	}
	calls := modctl.calls()
	if len(calls) != 2 {
		t.Fatalf("expected two modctl calls, got %v", calls)
	}
	if got := argv(t, calls[0]); !reflect.DeepEqual(got, []string{"pull", "ghcr.io/my-org/my-model:v1"}) {
		t.Errorf("modctl pull args = %v", got)
	}
	if got := argv(t, calls[1]); !reflect.DeepEqual(got, []string{"pull", "--plain-http", "127.0.0.1:5000/my-model:v1"}) {
		t.Errorf("modctl pull args for a local registry = %v", got)
	}
}

func TestModelPackPullReportsFailure(t *testing.T) {
	installFakeTool(t, "modctl", []string{""}, 3)
	err := (&ModelPackProvider{}).Pull("my-model:v1", "ghcr.io/my-org")
	if err == nil || !strings.Contains(err.Error(), "failed to pull with modctl") {
		t.Errorf("Pull() error = %v, want a modctl failure", err)
	}
}

// TestModelPackDelegatesManifestOperationsToORAS verifies the read and
// referrer operations run oras, never modctl.
func TestModelPackDelegatesManifestOperationsToORAS(t *testing.T) {
	p := &ModelPackProvider{}
	for _, tc := range []struct {
		name     string
		response string
		op       func() error
		wantArgs []string
	}{
		{
			"GetArtifactDigest", descriptor,
			func() error { _, err := p.GetArtifactDigest("my-model:v1", "ghcr.io/my-org"); return err },
			[]string{"manifest", "fetch", "--descriptor", "ghcr.io/my-org/my-model:v1"},
		},
		{
			"FetchManifestAnnotations", storedManifest,
			func() error { _, err := p.FetchManifestAnnotations("ghcr.io/my-org/my-model:v1"); return err },
			[]string{"manifest", "fetch", "ghcr.io/my-org/my-model:v1"},
		},
		{
			"GetReferrers", `{"referrers":[]}`,
			func() error { _, err := p.GetReferrers("my-model:v1", "ghcr.io/my-org", "t"); return err },
			[]string{"discover", "--artifact-type", "t", "--format", "json", "ghcr.io/my-org/my-model:v1"},
		},
		{
			"PushReferrer", "",
			func() error { return p.PushReferrer("my-model:v1", "ghcr.io/my-org", "t", []byte("{}"), nil) },
			[]string{"attach", "ghcr.io/my-org/my-model:v1", "--artifact-type", "t", "referrer.json:t"},
		},
		{
			"Search", `{"manifests":[]}`,
			func() error { _, err := p.Search("ghcr.io/my-org", NewSearchQuery()); return err },
			[]string{"repo", "ls", "ghcr.io/my-org"},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			modctl := installFakeTool(t, "modctl", []string{""}, 0)
			oras := installFakeTool(t, "oras", []string{tc.response}, 0)
			if err := tc.op(); err != nil {
				t.Fatalf("%s() error = %v", tc.name, err)
			}
			if calls := modctl.calls(); len(calls) != 0 {
				t.Errorf("%s() ran modctl: %v", tc.name, calls)
			}
			calls := oras.calls()
			if len(calls) == 0 {
				t.Fatalf("%s() did not run oras", tc.name)
			}
			if got := argv(t, calls[0]); !reflect.DeepEqual(got, tc.wantArgs) {
				t.Errorf("oras args = %v, want %v", got, tc.wantArgs)
			}
		})
	}
}

func TestMergeManifestAnnotations(t *testing.T) {
	t.Run("adds and overwrites", func(t *testing.T) {
		out, err := mergeManifestAnnotations([]byte(`{"schemaVersion":2,"config":{"digest":"sha256:a"},"annotations":{"keep":"1","k":"old"}}`),
			map[string]string{"k": "new", "added": "2"})
		if err != nil {
			t.Fatal(err)
		}
		var got map[string]interface{}
		if err := json.Unmarshal(out, &got); err != nil {
			t.Fatal(err)
		}
		want := map[string]interface{}{
			"schemaVersion": float64(2),
			"config":        map[string]interface{}{"digest": "sha256:a"},
			"annotations":   map[string]interface{}{"keep": "1", "k": "new", "added": "2"},
		}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("merged = %v, want %v", got, want)
		}
	})
	t.Run("manifest without annotations", func(t *testing.T) {
		for _, raw := range []string{`{"schemaVersion":2}`, `{"schemaVersion":2,"annotations":null}`} {
			out, err := mergeManifestAnnotations([]byte(raw), map[string]string{"k": "v"})
			if err != nil {
				t.Fatal(err)
			}
			if !strings.Contains(string(out), `"annotations":{"k":"v"}`) {
				t.Errorf("merged %s = %s", raw, out)
			}
		}
	})
	t.Run("invalid manifest", func(t *testing.T) {
		if _, err := mergeManifestAnnotations([]byte("nope"), nil); err == nil {
			t.Error("expected an error for invalid JSON")
		}
	})
}

func TestPlainHTTPArgs(t *testing.T) {
	for registry, want := range map[string]bool{
		"localhost:5000":         true,
		"localhost":              true,
		"127.0.0.1:5000/my-org":  true,
		"[::1]:5000":             true,
		"ghcr.io/my-org":         false,
		"registry.local:5000":    false,
		"notlocalhost.example":   false,
		"localhost.example.com":  false,
		"registry.example.com/a": false,
	} {
		got := len(plainHTTPArgs(registry)) == 1
		if got != want {
			t.Errorf("plainHTTPArgs(%q) plain-http = %v, want %v", registry, got, want)
		}
	}
}

func TestModelNameOf(t *testing.T) {
	for artifact, want := range map[string]string{
		"my-model:v1":               "my-model",
		"my-org/my-model:v1":        "my-model",
		"my-org/my-model@sha256:ab": "my-model",
		"my-model":                  "my-model",
	} {
		if got := modelNameOf(artifact); got != want {
			t.Errorf("modelNameOf(%q) = %q, want %q", artifact, got, want)
		}
	}
}

func TestModelfileForQuotesPathsWithSpaces(t *testing.T) {
	got := string(modelfileFor("m", []string{"my weights.bin", "notes.txt", "train.py", "cfg.yaml"}))
	want := "# Generated by model-cli for modctl build\nNAME m\nMODEL \"my weights.bin\"\nDOC notes.txt\nCODE train.py\nCONFIG cfg.yaml\n"
	if got != want {
		t.Errorf("modelfileFor =\n%s\nwant\n%s", got, want)
	}
}
